/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://ixklwvn73bbrpj4aasxv6f4lue.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nj36ob4kdnaf7jegfk4ij5htky",
    "aws_cloud_logic_custom": [
        {
            "name": "crawlerapi",
            "endpoint": "https://qeirc5jml9.execute-api.eu-west-1.amazonaws.com/prod",
            "region": "eu-west-1"
        }, 
        {
            "name": "datalego",
            "endpoint": "https://274fsh5l14.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }, 
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:e6af9463-f9cb-497f-9899-8f3b22ac27eb",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N8udMNHWv",
    "aws_user_pools_web_client_id": "4b8svikufrnjrjp83vg9ohtdro",
    "oauth": {}
};


export default awsmobile;
